// Run against the Vite dev server. PLAYWRIGHT_MODULE can point to a shared runtime.
import assert from "node:assert/strict";
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || "playwright");
const browser = await chromium.launch({ channel: "chrome", headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1280, height: 800 }, acceptDownloads: true });
  const page = await context.newPage();
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(process.env.TEST_URL || "http://127.0.0.1:5173");
  await page.locator("[data-menu-action=options]").click();
  await page.locator("#utility-tools-option").check();
  await page.locator("#clock-enabled-option").check();
  assert.equal(await page.evaluate(() => localStorage.getItem("nelg-utility-tools-enabled")), "true");
  await page.locator("#menu-back").click();
  await page.locator("[data-menu-action=start]").click();
  await page.locator(".utility-toggle").waitFor();
  const toggleRect = await page.locator(".utility-toggle").boundingBox();
  const clockRect = await page.locator(".game-clock").boundingBox();
  assert.ok(toggleRect.x + toggleRect.width <= clockRect.x);
  assert.equal(toggleRect.width, toggleRect.height);
  await page.locator(".utility-toggle").click();
  await page.evaluate(() => {
    window.utilityTestKeys = 0;
    document.addEventListener("keydown", () => window.utilityTestKeys++);
  });
  const canvas = page.locator(".utility-drawing");
  const rect = await canvas.boundingBox();
  const pixel = (x, y) => page.locator(".utility-drawing").evaluate((el, [x, y]) => Array.from(el.getContext("2d").getImageData(x, y, 1, 1).data), [x, y]);
  const at = (x, y) => ({ x: rect.x + x * rect.width / 800, y: rect.y + y * rect.height / 600 });
  const start = at(100, 200), end = at(200, 200);
  await page.mouse.move(start.x, start.y); await page.mouse.down();
  await page.mouse.move(end.x, end.y, { steps: 5 }); await page.mouse.up();
  assert.ok((await pixel(150, 200))[3] > 0);
  await page.keyboard.press("Control+z");
  assert.equal((await pixel(150, 200))[3], 0);
  await page.keyboard.press("Control+y");
  assert.ok((await pixel(150, 200))[3] > 0);
  await page.keyboard.press("Control+z");
  await page.keyboard.press("Control+Shift+z");
  assert.ok((await pixel(150, 200))[3] > 0);
  await page.locator("[data-action=undo]").click();
  assert.equal((await pixel(150, 200))[3], 0);
  await page.locator("[data-tool=fill]").click();
  await page.mouse.click(start.x, start.y);
  assert.deepEqual(await pixel(150, 200), [34, 139, 34, 255]);
  assert.ok(await page.locator("[data-action=redo]").isDisabled());
  await page.locator("[data-tool=eraser]").click();
  await page.mouse.click(start.x, start.y);
  assert.equal((await pixel(100, 200))[3], 0);
  await page.locator("[data-action=clear]").click();
  assert.equal((await pixel(150, 200))[3], 0);
  await page.locator("[data-tool=fill]").click();
  assert.equal(await page.locator("[data-field=fill-background]").isChecked(), false);
  await page.locator("#level-screen").evaluate(screen => {
    const region = document.createElement("div");
    region.id = "utility-fill-test-region";
    region.style.cssText = "position:absolute;left:80px;top:180px;width:140px;height:100px;background:rgb(255,0,0);z-index:1000";
    screen.append(region);
  });
  await page.locator("[data-field=fill-background]").check();
  await page.mouse.click(start.x, start.y);
  await page.getByRole("status").filter({ hasText: "Puzzle region filled" }).waitFor();
  assert.deepEqual(await pixel(150, 220), [34, 139, 34, 255]);
  assert.equal((await pixel(250, 220))[3], 0);
  await page.locator("[data-action=undo]").click();
  assert.equal((await pixel(150, 220))[3], 0);
  assert.equal(await page.locator("#utility-fill-test-region").evaluate(el => getComputedStyle(el).backgroundColor), "rgb(255, 0, 0)");
  await page.locator("#utility-fill-test-region").evaluate(el => el.remove());
  const hiddenPixel = await page.locator("#level-screen").evaluate(async screen => {
    screen.style.background = "#fff";
    const img = new Image();
    img.id = "utility-precision-test-image";
    img.src = "/assets/images/level31a.png";
    img.style.cssText = "position:absolute;left:272px;top:215px;width:256px;height:256px;z-index:1000";
    await img.decode();
    screen.append(img);
    const canvas = document.createElement("canvas");
    canvas.width = canvas.height = 256;
    const ctx = canvas.getContext("2d");
    ctx.drawImage(img, 0, 0);
    const data = ctx.getImageData(0, 0, 256, 256).data;
    for (let i = 0; i < data.length; i += 4) {
      if (data[i] === 255 && data[i + 1] === 255 && data[i + 2] === 252 && data[i + 3] === 255) {
        return { x: 272 + (i / 4) % 256, y: 215 + Math.floor(i / 4 / 256) };
      }
    }
    throw new Error("Level 31 hidden-color pixel not found");
  });
  await page.locator("[data-action=precision-fill]").click();
  assert.equal(await page.locator("[data-field=fill-tolerance]").inputValue(), "0");
  assert.equal(await page.locator("[data-field=fill-contiguous]").isChecked(), false);
  await page.mouse.click(start.x, start.y);
  await page.getByRole("status").filter({ hasText: "Puzzle region filled" }).waitFor();
  assert.deepEqual(await pixel(100, 200), [34, 139, 34, 255]);
  assert.equal((await pixel(hiddenPixel.x, hiddenPixel.y))[3], 0, "Precision fill must leave Level 31's near-white artwork visible");
  await page.locator("[data-action=undo]").click();
  assert.equal((await pixel(100, 200))[3], 0);
  await page.locator("#utility-precision-test-image").evaluate(el => el.remove());
  await page.locator("[data-tool=text]").click();
  const gameFonts = await page.locator('[data-field=font] optgroup[label="Game fonts"] option').evaluateAll(options => options.map(option => option.value));
  assert.equal(gameFonts.length, 17);
  for (const font of ["NELG Chiller", "NELG Nexa", "NELG Wanted Sans", "NELG Matisse", "NELG Vivaldi"]) assert.ok(gameFonts.includes(font));
  await page.locator("[data-field=font]").selectOption("NELG Nexa");
  await page.locator("[data-field=text]").fill("Puzzle note");
  await page.mouse.click(start.x, start.y);
  await page.getByRole("status").filter({ hasText: "Text placed." }).waitFor();
  assert.ok(await page.evaluate(() => document.fonts.check('28px "NELG Nexa"')));
  assert.ok(await canvas.evaluate(el => el.getContext("2d").getImageData(100, 200, 200, 60).data.some(value => value !== 0)));
  await page.locator("[data-tool=notes]").click();
  const drawingBeforeNoteUndo = await canvas.evaluate(el => el.toDataURL());
  await page.locator("[data-field=note]").focus();
  await page.keyboard.type("temporary note");
  await page.keyboard.press("Control+z");
  assert.notEqual(await page.locator("[data-field=note]").inputValue(), "temporary note");
  await page.keyboard.press("Control+y");
  assert.equal(await page.locator("[data-field=note]").inputValue(), "temporary note");
  assert.equal(await canvas.evaluate(el => el.toDataURL()), drawingBeforeNoteUndo);
  assert.deepEqual(await page.locator('[data-field=note-font] optgroup[label="Game fonts"] option').evaluateAll(options => options.map(option => option.value)), gameFonts);
  const note = "# Test note\n\n**Bold** and `code`\n\n<script>window.noteXss=1</script>\n[bad](javascript:alert(1))";
  await page.locator("[data-field=note]").fill(note);
  await page.locator("[data-field=note]").press("ArrowLeft");
  assert.equal(await page.evaluate(() => window.utilityTestKeys), 0);
  await page.locator("[data-field=note-font]").selectOption("Georgia");
  await page.locator("[data-action=preview]").click();
  assert.equal(await page.locator(".utility-tools__markdown h1").innerText(), "Test note");
  assert.equal(await page.locator(".utility-tools__markdown script, .utility-tools__markdown a[href^='javascript:']").count(), 0);
  assert.equal(await page.evaluate(() => localStorage.getItem("nelg-utility-note")), note);
  const noteDownload = page.waitForEvent("download");
  await page.locator("[data-action=download-note]").click();
  const downloadedNote = await noteDownload;
  assert.equal(downloadedNote.suggestedFilename(), "puzzle-notes.md");
  const stream = await downloadedNote.createReadStream();
  const chunks = []; for await (const chunk of stream) chunks.push(chunk);
  assert.equal(Buffer.concat(chunks).toString("utf8"), note);
  await page.locator("[data-tool=capture]").click();
  // Inspect clipboard payloads without replacing the developer's OS clipboard.
  await page.evaluate(() => {
    window.utilityClipboardWrites = [];
    Object.defineProperty(navigator, "clipboard", { configurable: true, value: {
      write: async items => {
        const blob = await items[0].getType("image/png");
        const bitmap = await createImageBitmap(blob);
        window.utilityClipboardWrites.push({ width: bitmap.width, height: bitmap.height });
        bitmap.close();
      },
    } });
  });
  const cropEnd = at(300, 320);
  await page.mouse.move(start.x, start.y); await page.mouse.down();
  await page.mouse.move(cropEnd.x, cropEnd.y, { steps: 5 }); await page.mouse.up();
  await page.locator("[data-capture-download]").waitFor({ timeout: 30000 });
  const dimensions = await page.locator(".utility-tools__preview").evaluate(el => ({ width: el.naturalWidth, height: el.naturalHeight }));
  assert.ok(dimensions.width >= 199 && dimensions.width <= 201);
  assert.ok(dimensions.height >= 119 && dimensions.height <= 121);
  await page.getByRole("status").filter({ hasText: "image copied to clipboard" }).waitFor();
  assert.deepEqual(await page.evaluate(() => window.utilityClipboardWrites), [dimensions]);
  await page.locator("[data-action=copy-capture]").click();
  await page.waitForFunction(() => window.utilityClipboardWrites.length === 2);
  await page.getByRole("status").filter({ hasText: "Image copied to clipboard." }).waitFor();
  assert.equal(await page.evaluate(() => window.utilityClipboardWrites.length), 2);
  await page.evaluate(() => { navigator.clipboard.write = async () => { throw new DOMException("Denied", "NotAllowedError"); }; });
  await page.locator("[data-action=copy-capture]").click();
  await page.getByRole("status").filter({ hasText: "Clipboard unavailable" }).waitFor();
  assert.ok(await page.locator(".utility-tools__preview").evaluate(img => {
    const canvas = document.createElement("canvas");
    canvas.width = canvas.height = img.naturalWidth;
    const ctx = canvas.getContext("2d");
    ctx.drawImage(img, 0, 0);
    return ctx.getImageData(0, 0, canvas.width, canvas.height).data.some((value, i) => i % 4 === 3 && value > 0);
  }));
  const pngDownload = page.waitForEvent("download");
  await page.locator("[data-capture-download]").click();
  assert.equal((await pngDownload).suggestedFilename(), "puzzle-capture.png");
  const savedDrawing = await canvas.evaluate(el => el.toDataURL());
  await page.locator(".utility-toggle").click();
  assert.equal(await canvas.isVisible(), false);
  assert.equal(await canvas.evaluate(el => el.toDataURL()), savedDrawing);
  await page.locator(".utility-toggle").click();
  assert.equal(await canvas.isVisible(), true);
  assert.equal(await canvas.evaluate(el => el.toDataURL()), savedDrawing);
  await page.locator("[data-action=close]").click();
  assert.equal(await canvas.isVisible(), false);
  assert.equal(await canvas.evaluate(el => getComputedStyle(el).pointerEvents), "none");
  await page.reload();
  await page.locator("[data-menu-action=start]").click();
  await page.locator(".utility-toggle").click();
  await page.locator("[data-tool=notes]").click();
  assert.equal(await page.locator("[data-field=note]").inputValue(), note);
  assert.equal(await page.locator("[data-field=note-font]").inputValue(), "Georgia");
  await page.setViewportSize({ width: 390, height: 844 });
  const panelRect = await page.locator(".utility-tools").boundingBox();
  assert.ok(panelRect.x >= 0 && panelRect.x + panelRect.width <= 390);
  assert.ok(panelRect.y + panelRect.height <= 844);
  if (process.env.UTILITY_SCREENSHOT) await page.screenshot({ path: process.env.UTILITY_SCREENSHOT });
  await page.locator("[data-action=minimize]").click();
  assert.ok((await page.locator(".utility-tools").boundingBox()).height < 100);
  const headerRect = await page.locator(".utility-tools header strong").boundingBox();
  await page.mouse.move(headerRect.x + 10, headerRect.y + 10); await page.mouse.down();
  await page.mouse.move(headerRect.x + 10, 45, { steps: 5 }); await page.mouse.up();
  assert.ok((await page.locator(".utility-tools").boundingBox()).y < 60);
  await page.reload();
  await page.locator("[data-menu-action=options]").click();
  await page.locator("#clock-enabled-option").uncheck();
  await page.locator("#menu-back").click();
  await page.locator("[data-menu-action=start]").click();
  assert.ok(await page.locator(".utility-toggle").isVisible());
  assert.equal(await page.locator(".game-clock").count(), 0);
  await page.reload();
  await page.locator("[data-menu-action=options]").click();
  await page.locator("#utility-tools-option").uncheck();
  await page.locator("#menu-back").click();
  await page.locator("[data-menu-action=start]").click();
  assert.equal(await page.locator(".utility-toggle").isVisible(), false);
  assert.equal(await page.locator(".utility-drawing").count(), 0);
  assert.deepEqual(errors, []);
  console.log("Passed: options, drawing, undo/redo, background fill, game fonts, notes, rectangular capture, automatic/manual clipboard payloads, clipboard denial fallback, PNG/MD downloads, mobile layout.");
  await context.close();
} finally { await browser.close(); }
