$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$rootGlyph = Split-Path -Parent $PSScriptRoot
$glyphSheet = [System.Drawing.Bitmap]::new((Join-Path $rootGlyph 'public/assets/handwriting/sheet.png'))
try {
  $glyphBands = @(@(0,127,120,'ABCDEFGH'), @(128,229,220,'IJKLMNOP'), @(230,341,320,'QRSTUVWX'), @(342,463,446,'YZ0123456'), @(464,599,560,'789?!.()-,'))
  $glyphLines = [System.Collections.Generic.List[string]]::new()
  $glyphLines.Add('// Generated by scripts/extract-handwriting.ps1 from the original 600 x 600 sheet.')
  $glyphLines.Add('// x, y, width, height, row baseline; keep original letter shapes and spacing.')
  $glyphLines.Add('export const HANDWRITING_GLYPHS: Readonly<Record<string, readonly [number, number, number, number, number]>> = {')
  foreach ($glyphBand in $glyphBands) {
    $glyphRanges = @(); $glyphStart = -1
    for ($gx = 0; $gx -le $glyphSheet.Width; $gx++) {
      $glyphHit = $false
      if ($gx -lt $glyphSheet.Width) {
        for ($gy = $glyphBand[0]; $gy -le $glyphBand[1]; $gy++) {
          if ($glyphSheet.GetPixel($gx,$gy).A -gt 16) { $glyphHit = $true; break }
        }
      }
      if ($glyphHit -and $glyphStart -lt 0) { $glyphStart = $gx }
      if (-not $glyphHit -and $glyphStart -ge 0) { $glyphRanges += ,@($glyphStart, ($gx - 1)); $glyphStart = -1 }
    }
    if ($glyphRanges.Count -ne $glyphBand[3].Length) { throw 'Glyph count mismatch; inspect the sheet layout.' }
    for ($gi = 0; $gi -lt $glyphRanges.Count; $gi++) {
      $range = $glyphRanges[$gi]; $minY = 600; $maxY = 0
      for ($gx = $range[0]; $gx -le $range[1]; $gx++) {
        for ($gy = $glyphBand[0]; $gy -le $glyphBand[1]; $gy++) {
          if ($glyphSheet.GetPixel($gx,$gy).A -gt 16) { $minY = [Math]::Min($minY,$gy); $maxY = [Math]::Max($maxY,$gy) }
        }
      }
      $left = [Math]::Max(0,$range[0]-1); $top = [Math]::Max(0,$minY-1)
      $width = $range[1]-$left+2; $height = $maxY-$top+2
      $glyphLines.Add('  "'+$glyphBand[3][$gi]+'": ['+$left+', '+$top+', '+$width+', '+$height+', '+$glyphBand[2]+'],')
    }
  }
  $glyphLines.Add('};')
  [System.IO.File]::WriteAllLines((Join-Path $rootGlyph 'src/core/handwritingGlyphs.ts'), $glyphLines, [System.Text.UTF8Encoding]::new($false))
} finally { $glyphSheet.Dispose() }
